### ISSUE TITLE
AWSインフラストラクチャ構築 - CloudFormation & デプロイ環境セットアップ

### ISSUE THREAD

**Issue by hiraaaken** [hiraaaken/konro#4]
## 概要
KonroのAWSインフラストラクチャをIaCで構築する（CloudFormation + 複数環境対応）

## 技術スタック
- **IaC**: AWS CloudFormation (SAM)
- **コンピュート**: AWS Lambda
- **API**: Amazon API Gateway
- **データベース**: Amazon DynamoDB
- **AI/ML**: Amazon Bedrock
- **ホスティング**: Amazon S3 + CloudFront
- **環境**: dev/staging/prod

### 1. CloudFormation テンプレート作成
- [ ] `template.yaml` (SAM形式) 作成
- [ ] パラメータ定義（環境別設定）
- [ ] 出力値定義（APIエンドポイント等）

### 2. Lambda関数リソース定義
```yaml
Resources:
  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: presentation/handlers/chat-handler.handler
      Runtime: nodejs20.x
      Environment:
        Variables:
          DYNAMODB_TABLE: \!Ref ChatTable
          BEDROCK_REGION: \!Ref AWS::Region
```

### 3. API Gateway設定
- [ ] REST API定義
- [ ] CORS設定
- [ ] APIキー認証設定
- [ ] レート制限設定
- [ ] リクエストバリデーション

### 4. DynamoDB テーブル定義
- [ ] ChatSession テーブル設計
- [ ] パーティションキー/ソートキー設計
- [ ] TTL設定（セッション自動削除）
- [ ] インデックス設計

### 5. S3 + CloudFront (フロントエンド)
- [ ] S3バケット設定（静的サイトホスティング）
- [ ] CloudFront ディストリビューション
- [ ] SSL証明書設定
- [ ] キャッシュポリシー設定

### 6. IAM ロール・ポリシー設定
- [ ] Lambda実行ロール
- [ ] DynamoDB アクセス権限
- [ ] Bedrock アクセス権限
- [ ] CloudWatch Logs権限

### 7. 環境別設定ファイル
- [ ] `samconfig.toml` - 環境別デプロイ設定
```toml
[default.global.parameters]
stack_name = "konro"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[dev.deploy.parameters]
stack_name = "konro-dev"
s3_prefix = "konro-dev"
region = "ap-northeast-1"
parameter_overrides = "Environment=dev"

[staging.deploy.parameters]
stack_name = "konro-staging"
s3_prefix = "konro-staging"
region = "ap-northeast-1"
parameter_overrides = "Environment=staging"

[prod.deploy.parameters]
stack_name = "konro-prod"
s3_prefix = "konro-prod"
region = "ap-northeast-1"
parameter_overrides = "Environment=prod"
```

### 8. セキュリティ設定
- [ ] VPC設定（必要に応じて）
- [ ] セキュリティグループ
- [ ] WAF設定（本番環境）
- [ ] 暗号化設定（DynamoDB, S3）

### 9. モニタリング・ログ設定
- [ ] CloudWatch Logs設定
- [ ] CloudWatch Metrics設定
- [ ] X-Ray トレース設定
- [ ] アラーム設定

### 10. デプロイスクリプト
- [ ] `deploy.sh` - 環境別デプロイスクリプト
- [ ] `rollback.sh` - ロールバックスクリプト
- [ ] `cleanup.sh` - リソース削除スクリプト

## ディレクトリ構造
```
infrastructure/
├── template.yaml           # メインのCloudFormationテンプレート
├── samconfig.toml         # SAM設定ファイル
├── parameters/            # 環境別パラメータ
│   ├── dev.json
│   ├── staging.json
│   └── prod.json
├── scripts/               # デプロイスクリプト
│   ├── deploy.sh
│   ├── rollback.sh
│   └── cleanup.sh
└── docs/                  # インフラドキュメント
    ├── architecture.md
    └── deployment.md
```

## 成功条件
- [ ] `sam build` でビルド成功
- [ ] `sam deploy --config-env dev` でdev環境デプロイ成功
- [ ] API Gateway経由でLambda関数呼び出し成功
- [ ] DynamoDB読み書き成功
- [ ] CloudFront経由でS3コンテンツ配信成功
- [ ] 環境別デプロイ（dev/staging/prod）成功

## 参考
- [AWS SAM](https://docs.aws.amazon.com/serverless-application-model/)
- [API Gateway](https://docs.aws.amazon.com/apigateway/)
- [DynamoDB](https://docs.aws.amazon.com/dynamodb/)
- [CloudFront](https://docs.aws.amazon.com/cloudfront/)

🤖 Generated with [Claude Code](https://claude.ai/code)
